# active profile
spring:
   application:
     name: mysite
   profiles:
      active: development
      
---
#
# common configuration
#
spring:
   mvc:
      # path pattern used for static resources
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
         
   # template engine: thymeleaf    
   thymeleaf:
      prefix: classpath:templates/
      check-template-location: true
      mode: HTML
      suffix: .html
      cache: false
   
   servlet:
      multipart:
         enabled: true
         max-file-size: 20MB
         max-request-size: 100MB

# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml
         
---
#
# development profile configuration
#
spring:
   config:
      activate:
         on-profile: development
         
   web:
      resources:
         static-locations: classpath:/static/, file:/Users/sangeonpark/upload-images/
   devtools:
      livereload:
         enabled: true
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.55:3307/webdb?characterEncoding=utf8
      username: webdb
      password: webdb   

# server
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
         
# logging
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO

---
#
# production profile configuration
#
spring:
   config:
      activate:
         on-profile: production
         
   web:
      resources:
         static-locations: classpath:/static/, file:/mysite-images/
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.55:3307/webdb?characterEncoding=utf8
      username: webdb
      password: webdb   
         
server:
   port: 8881
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
         
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
   file:
      name: logs/${spring.application.name}.log
      max-history: 30
   level:
      root: INFO
      me:
         kickscar:
            mysite:
               exception: ERROR
